#!/usr/bin/env python3
import argparse
import os
import random
import time
from pathlib import Path

import wandb


def load_examples_env():
    env_path = Path(__file__).resolve().parents[1] / ".env"
    if not env_path.exists():
        return

    for line in env_path.read_text(encoding="utf-8").splitlines():
        raw = line.strip()
        if not raw or raw.startswith("#") or "=" not in raw:
            continue
        key, value = raw.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def parse_args():
    parser = argparse.ArgumentParser(description="Create a sample W&B run for MLflow conversion demos.")
    parser.add_argument("--project", type=str, default=os.environ.get("WANDB_PROJECT", "wandb2mlflow-demo"))
    parser.add_argument("--entity", type=str, default=os.environ.get("WANDB_ENTITY", ""))
    parser.add_argument("--run-name", type=str, default="wandb-example")
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--learning-rate", type=float, default=1e-3)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--weight-decay", type=float, default=1e-2)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--optimizer", type=str, default="adamw")
    parser.add_argument("--model-name", type=str, default="resnet18")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--sleep-sec", type=float, default=0.05)
    return parser.parse_args()


def main():
    load_examples_env()
    args = parse_args()

    init_kwargs = {
        "project": args.project,
        "name": args.run_name,
        "config": {
            "epochs": args.epochs,
            "learning_rate": args.learning_rate,
            "batch_size": args.batch_size,
            "weight_decay": args.weight_decay,
            "dropout": args.dropout,
            "optimizer": args.optimizer,
            "model_name": args.model_name,
            "seed": args.seed,
            "source": "wandb_example_for_mlflow_conversion",
        },
    }
    if args.entity:
        init_kwargs["entity"] = args.entity

    run = wandb.init(**init_kwargs)

    random.seed(args.seed)
    train_loss = 2.0
    train_acc = 0.2
    val_loss = 2.2
    val_acc = 0.18
    best_val_acc = 0.0
    start = time.time()

    for epoch in range(args.epochs):
        time.sleep(args.sleep_sec)
        train_loss *= random.uniform(0.86, 0.96)
        val_loss *= random.uniform(0.87, 0.98)
        train_acc = min(0.995, train_acc + random.uniform(0.015, 0.045))
        val_acc = min(0.99, val_acc + random.uniform(0.012, 0.04))
        lr = args.learning_rate * (0.95**epoch)
        grad_norm = max(0.05, random.uniform(0.2, 1.8) * (0.98**epoch))
        epoch_time_sec = random.uniform(0.15, 0.45)
        best_val_acc = max(best_val_acc, val_acc)

        wandb.log(
            {
                "train/loss": train_loss,
                "train/acc": train_acc,
                "val/loss": val_loss,
                "val/acc": val_acc,
                "val/best_acc": best_val_acc,
                "lr": lr,
                "grad_norm": grad_norm,
                "system/epoch_time_sec": epoch_time_sec,
                "epoch": epoch,
            },
            step=epoch,
        )

    run.summary["final_train_loss"] = train_loss
    run.summary["final_train_acc"] = train_acc
    run.summary["final_val_loss"] = val_loss
    run.summary["final_val_acc"] = val_acc
    run.summary["best_val_acc"] = best_val_acc
    run.summary["total_runtime_sec"] = time.time() - start
    run.summary["note"] = "Run generated by examples/migration/wandb_example.py"

    run_id = run.id
    entity = run.entity or args.entity
    project = run.project or args.project
    run_url = getattr(run, "url", "")
    run.finish()

    print("W&B example run finished.")
    if run_url:
        print(f"Run URL: {run_url}")
    if entity and project and run_id:
        print(f"Run path for conversion: {entity}/{project}/{run_id}")
    else:
        print("Could not infer full run path automatically.")
        print("Use your W&B UI URL to identify <entity>/<project>/<run_id> for conversion.")


if __name__ == "__main__":
    main()
